---
name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.email "github.actions@samcaldwell.net"
          git config --local user.name "Sam Caldwell (automation)"

      - name: Determine current tag
        id: current_tag
        run: |
          
          if git describe --tags $(git log -n10 --pretty='%h') | head -n1 | awk -F\- '{print $1}'; then
            echo "::set-output name=tag::$(git describe --tags $(git log -n10 --pretty='%h') | head -n1 | awk -F\- '{print $1}')"
          else
            echo "::set-output name=tag::v0.0.0"
          fi

      - name: Increment version
        id: incremented_version
        run: |
          current_tag="${{ steps.current_tag.outputs.tag }}"
          major=$(echo "${current_tag#v}" | awk -F. '{print $1}')
          minor=$(echo "${current_tag#v}" | awk -F. '{print $2}')
          patch=$(echo "${current_tag#v}" | awk -F. '{print $3}')
          new_version="v${major}.${minor}.$((${patch}+1))"
          echo "::set-output name=version::${new_version}"

      - name: Create and push tag
        if: ${{ steps.current_tag.outputs.tag != steps.incremented_version.outputs.version }}
        run: |
          git tag ${{ steps.incremented_version.outputs.version }}
#          git push origin ${{ steps.incremented_version.outputs.version }}
